import { probeOllama } from '../bridge/ollama.mjs'
import { probeLocalVoiceCapabilities } from '../bridge/orbia/local-voice-probe.mjs'
import { probeSpeakerDiarization } from '../bridge/orbia/speaker-diarization-probe.mjs'
import { teamsTranscriptCapabilities } from '../bridge/orbia/teams-transcript.mjs'

const voice = probeLocalVoiceCapabilities()
const diarization = probeSpeakerDiarization()
const teams = teamsTranscriptCapabilities()
const ollama = await probeOllama()

console.log('L.U.M.I.A. Meeting Intelligence Doctor')
console.log('--------------------------------------')
console.log('Phase:                   MI-04')
console.log('')
console.log('Capture:')
console.log(`  local microphone STT:   ${voice.stt.localAvailable ? 'READY' : 'MISSING'}`)
console.log('  browser system audio:   READY · user share permission required')
console.log('  raw audio retention:    OFF by default')
console.log('')
console.log('Speaker identity:')
console.log(`  diarization runtime:    ${diarization.available ? 'READY' : 'MISSING'}`)
console.log(`  persistent room tracker: ${diarization.available ? 'READY · adaptive clustering' : 'MISSING'}`)
console.log('  short-utterance embed:   READY · meeting-only policy')
console.log('  short-turn recovery:     READY · established speakers only')
console.log('  duplicate consolidation: READY')
console.log('  expected participant cap: READY · optional')
console.log('  other-person profiles:   NOT PERSISTED')
console.log('  explicit platform name: READY')
console.log('  live Teams name source: ADAPTER INPUT READY · source integration pending')
console.log('')
console.log('Teams:')
console.log(`  WebVTT parser:           ${teams.postMeetingGraphTranscript ? 'READY' : 'MISSING'}`)
console.log('  Graph auth:              EXTERNAL / tenant-controlled')
console.log('  post-meeting reconcile: READY')
console.log('')
console.log('Meeting intelligence:')
console.log(`  local Ollama:            ${ollama.ok ? 'READY' : 'MISSING'}`)
console.log('  summary/tasks/decisions: READY when Ollama is available')
console.log('  query-the-meeting:       READY when Ollama is available')
console.log('')
console.log('Persistence:')
console.log('  append-only JSONL:       READY')
console.log('  checkpoints:             READY')
console.log('  Markdown/WebVTT export:  READY')
console.log('')
console.log('Console:')
console.log('  http://127.0.0.1:8787/meeting')
